# Generated by Django 2.0.8 on 2018-08-22 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('product_date', models.DateField(verbose_name='product date')),
                ('fuel_type', models.CharField(choices=[('D', 'Diesel'), ('P', 'Petrol'), ('L', 'LPG')], default='P', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='MileageHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.IntegerField()),
                ('date', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarManagment.Car')),
            ],
        ),
    ]
