# Generated by Django 2.0.8 on 2018-08-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarManagment', '0002_auto_20180822_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='model',
        ),
        migrations.AddField(
            model_name='car',
            name='model_name',
            field=models.CharField(default='', max_length=200, verbose_name='model'),
            preserve_default=False,
        ),
    ]
