# Generated by Django 2.0.8 on 2018-08-22 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarManagment', '0004_auto_20180822_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicehistory',
            options={'verbose_name_plural': 'Service histories'},
        ),
    ]
